export const LGND_ADDRESS = process.env.REACT_APP_ADDRESS_LGND;
export const PLATFORM_ADDRESS = process.env.REACT_APP_ADDRESS_PLATFORM;
export const NFT_ADDRESS = process.env.REACT_APP_ADDRESS_NFT;
export const NFT_MINTING_ADDRESS = process.env.REACT_APP_ADDRESS_NFT_MINTING;